import 'package:flutter/material.dart';

List<String> textList = [
  "Podcasts",
  "Live Events",
  "Made For You",
  "New Releases",
  "Hindi",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Charts",
  "Pop",
  "Indie",
  "Trending",
  "Love",
  "Discover",
  "Radio",
  "Mood",
  "Party",
  "Devotional",
  "Decades",
  "Hio-Hop",
];
List<String> imageList = [
  "assets/images/all.jpg",
  "assets/images/all23.jpg",
  "assets/images/all6.jpg",
  "assets/images/all17.jpg",
  "assets/images/all25.jpg",
  "assets/images/all22.jpg",
  "assets/images/all23.jpg",
  "assets/images/all24.jpg",
  "assets/images/all25.jpg",
  "assets/images/all17.jpg",
  "assets/images/all22.jpg",
  "assets/images/all23.jpg",
  "assets/images/all.jpg",
  "assets/images/all17.jpg",
  "assets/images/all23.jpg",
  "assets/images/all6.jpg",
  "assets/images/all17.jpg",
  "assets/images/all25.jpg",
  "assets/images/all22.jpg",
  "assets/images/all.jpg",
];
List<Color> colList = [
  Colors.green.shade600,
  Colors.deepPurpleAccent,
  Colors.indigo,
  Colors.blue,
  Colors.blueGrey,
  Colors.pink,
  Colors.lime,
  Colors.deepPurpleAccent,
  Colors.blueAccent,
  Colors.deepOrangeAccent,
  Colors.redAccent,
  Colors.grey,
  Colors.brown,
  Colors.orange,
  Colors.lightBlueAccent,
  Colors.lightGreen,
  Colors.red,
  Colors.cyan,
  Colors.grey,
  Colors.purpleAccent,
];
